### ISSUE TITLE
Revisar en Code las Ramas Main and Develop

### ISSUE THREAD

**Issue by Lucas-Balduzzi** [Lucas-Balduzzi/Programador_TSWAD#15]
Si leen esto,
Faltaría que revisen su rama para cerrar esta ISSUE.

**Comment by jochigallotti37** [comment]
> Chicos, estuve toqueteando esto de Github, y Github Desktop. Aún no interiorice en Git Bash. Vean las ramas que he creado. Una es la rama Main. La original y final de todo los cambios recopilados. Desde Develop pueden crear una rama nueva o bien hacer cambios sobre ella, que luego serán pasadas a Main con un merge pull request. Una vez seleccionada la rama Develop, vuelvan a pinchar en la seleccion de rama, escriban "su_nombre-Developer" y click abajo donde dice "Create a new branch:<...> from Develop". Al crear su propia rama, cada uno puede realizar cambios en ella sin afectar a los cambios del resto. luego se revisan y se acoplan a la rama final "Develop", y despues a la Main, una vez revisado todo como producto final del progama. Al menos es lo que entendi. Cualquier cosa, me escriben.

<Perfecto Lucas, esta muy claro y muy bien entendido por lo que nos comentas.
