### ISSUE TITLE
Generar resumen Base de Datos

### ISSUE THREAD

**Issue by Lucas-Balduzzi** [Lucas-Balduzzi/Programador_TSWAD#4]
Glosario
Enlaces a sitios
canales recomendados YTube
demas info
https://drive.google.com/file/d/19t6Su21YJE3yGY3x903SBKeLGaINgIKJ/view

**Comment by SilviaCarinaMonzon** [comment]
Agregue enlace de clase sincronica

**Comment by SilviaCarinaMonzon** [comment]
Agregue enlace de clase sincronica de ISPC
